codecov: 
  token: 11740e29-ae37-4e08-ad1c-2019b2b7f652
comment:                  # this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
coverage:
  status:
    patch:
      default:
        target: 100%
        threshold: 0%
        informational: false
ignore:
  - "setup.py"
  - "test/*"
  - "test/**/*.py"
