---
system_name: 'lens_system4'

band:
  - 'F390W'

pixel_size : 0.04

model:
  lens:
    - 'SIE' # the first mass profile needs to be for the deflector
             # as required by `lenstronomy`
    - 'SHEAR_GAMMA_PSI'
  lens_light:
    - 'SERSIC_ELLIPSE'
  source_light:
    - 'SERSIC_ELLIPSE'
  point_source: [] # 'LENSED_POSITION', 'SOURCE_POSITION'

lens_option:
  centroid_init: [0.04, -0.04]
  # Centroid_bound:
  constrain_position_angle_from_lens_light: 15
  # Provides a prior to push the position angle difference between 
  # lens mass and lens light to be smaller than a certain threshold. The 
  # default position angle difference threshold is 15 degrees.
  limit_mass_eccentricity_from_light: true
  # Provides a prior to push the lens light axis ratio to be smaller
  # than the lens mass, i.e., penalizes q_L - q_M > threshold). The
  # default threshold is 0.0

lens_light_option:
  fix: {0: {'n_sersic': 4.}} # fix n_sersic to 4. for 0-th light profile

source_light_option:
  n_max: [2] # array with n_max for each band

point_source_option:
  ra_init: []
  dec_init: []
  bound: 0.

kwargs_constraints:
  joint_lens_with_light: [[0, 0, ['center_x', 'center_y']]]

fitting:
  psf_iteration: false
  psf_iteration_settings:
    # num_iter: 20
    # psf_iter_factor: 0.5
    # psf_symmetry: 4
    # block_center_neighbour: 0.

  pso: true
  pso_settings:
    num_particle: 2
    num_iteration: 2

  sampling: true
  sampler: 'MCMC'
  mcmc_settings:
    burnin_step : 2
    iteration_step: 2
    walker_ratio: 2

kwargs_model:

kwargs_numerics:
  supersampling_factor: [3] # list specifying for each band

guess_params:
  lens:
    0:
      theta_E: 1.2
      e1: 0.05
      e2: -0.05

mask:
  size: [120] # 1d array, number of pixel for each band
  ra_at_xy_0: [2.4] # 1d array, for each band
  dec_at_xy_0: [-2.4] # 1d array, for each band
  centroid_offset: [[0., 0]]
  # 2d array, [ra_at_xy_0, dec_at_xy_0] to add to deflector centroid
  radius: [2.] # 1d array, radius in arcsec for each band
  transform_matrix: [[[-4.00004004e-02, -2.74607936e-07],
                     [-2.67119793e-07,  3.99999886e-02]]]
  # same transform_pix2angle` in kwargs_data, 3d array, for each band
  provided:
  # actual masks, 3d array with dimension (band, x, y), if
  # provided everything above will be ignored




