---
lens_name: 'lens_system5'

band: ['F390W']

model:
  lens: ['EPL', 'SHEAR_GAMMA_PSI'] # the first mass profile needs to be for the deflector as required by `lenstronomy`
  lens_light: ['SERSIC_ELLIPSE']
  source_light: ['SHAPELETS']
  point_source: ['LENSED_POSITION'] # 'LENSED_POSITION', 'SOURCE_POSITION'

# lens_option:
#   centroid_init: [0.0, 0.0]

lens_light_option:
  fix: {0: {'n_sersic': 4.}} # fix n_sersic to 4. for 0-th light profile

source_light_option:
  n_max: [4] # array with n_max for each band

point_source_option:
  ra_init: [1., 0., 1., 0.]
  dec_init: [0., 1., 0., -1.]
  bound: 0.1

fitting:
  psf_iteration: true
  psf_iteration_settings:
    stacking_method: median
    num_iter: 20
    psf_iter_factor: 0.5
    psf_symmetry: 4
    block_center_neighbour: 0.5
    keep_psf_variance_map: true

  pso: true
  pso_settings:
    num_particle: 20
    num_iteration: 50

  sampling: true
  sampler: emcee
  sampler_settings: # keywords to be sent to lenstronomy.Workflow.fitting_sequence.FittingSequence.mcmc()
    n_burn : 0
    n_run: 100
    walkerRatio: 2

numeric_option:
  supersampling_factor: [2]
