---
lens_name: 'lens_system_mge'

band:
  - 'F390W'

model:
  lens:
    - 'EPL'
    - 'SHEAR_GAMMA_PSI'
  lens_light:
    - 'MGE_SET_ELLIPSE'
  source_light:
    - 'SHAPELETS'

lens_option:
  centroid_init: [0.04, -0.04]

lens_light_option:
  mge_config:
    0:
      n_comp: 20

source_light_option:
  n_max: [4]

fitting:
  pso: true
  pso_settings:
    num_particle: 20
    num_iteration: 50

  sampling: false
  sampler: emcee
  sampler_settings: null

kwargs_numerics:
  supersampling_factor: [2]
