lens_name: lens_system2
band:
- F390W
model:
  lens:
  - EPL
  - SHEAR_GAMMA_PSI
  lens_light:
  - SERSIC_ELLIPSE
  source_light:
  - SERSIC_ELLIPSE
  - SHAPELETS
  point_source: []
lens_option:
  centroid_init:
  - 0.0
  - 0.0
  centroid_bound: 0.2
lens_light_option:
  fix:
    0:
      n_sersic: 4.0
source_light_option:
  n_max:
  - 6
satellites:
  centroid_init: []
  centroid_bound: 0.25
guess_params:
  lens:
    0:
      theta_E: 1.2520267522415003
numeric_option:
  supersampling_factor:
  - 3
fitting:
  pso: true
  pso_settings:
    num_particle: 4
    num_iteration: 2
  psf_iteration: false
  psf_iteration_settings: null
  sampling: false
  sampler: emcee
  sampler_settings: null
