---
lens_name: 'lens_system1'

band: ['F390W']

model:
  lens: ['EPL', 'SHEAR_GAMMA_PSI']
  lens_light: ['SERSIC_ELLIPSE']
  source_light: ['SERSIC_ELLIPSE']
  point_source: [] # 'LENSED_POSITION', 'SOURCE_POSITION'

lens_option:
  centroid_init: [0.04, -0.04]
  # initial guess for the deflector centroid in arcsec
  centroid_bound: 0.2
  # uniform bound (plus/minus from the init values) for the deflector centroid in arcsec
  limit_mass_pa_from_light: 15
  # Optional upper limit to constrain the position angle difference between 
  # deflector's mass and light to be smaller than the given threshold
  limit_mass_q_from_light: 0
  # Optional constraint on the light axis ratio to be smaller
  # than that of the mass, i.e., imposes q_M > q_L - limit_mass_eccentricity_from_light.

lens_light_option:
  fix: {0: {'n_sersic': 4.}} # fix n_sersic to 4. for 0-th light profile

source_light_option:
  n_max: [2] # array with n_max for each band

point_source_option:
  ra_init: []
  dec_init: []
  bound: 0.

kwargs_constraints:
  joint_lens_with_light: [[0, 0, ['center_x', 'center_y']]]

fitting:
  psf_iteration: false
  psf_iteration_settings:
    # num_iter: 20
    # psf_iter_factor: 0.5
    # psf_symmetry: 4
    # block_center_neighbour: 0.

  pso: true
  pso_settings:
    num_particle: 2
    num_iteration: 2

  sampling: true
  sampler: "emcee"
  sampler_settings: # keywords to be sent to lenstronomy.Workflow.fitting_sequence.FittingSequence.mcmc()
    n_burn : 2
    n_run: 2
    walkerRatio: 2

kwargs_model:

kwargs_numerics:
  supersampling_factor: [3] # list specifying for each band

guess_params:
  lens:
    0:
      theta_E: 1.2
      e1: 0.05
      e2: -0.05

mask:
  centroid_offset: [[0., 0]]
  # 2d array, [ra_at_xy_0, dec_at_xy_0] to add to deflector centroid
  radius: [2.] # 1d array, radius in arcsec for each band
  # same transform_pix2angle` in kwargs_data, 3d array, for each band
  provided: False
  # if actual masks is provided in the masks folder, in individual .npy files for each filter 
  # if provided everything the mask specifications will be ignored 
